### ISSUE TITLE
[Guardrails] Probabilistic Proofs - Proof Verification Data

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket-core#1516]
## Objective

To evaluate the viability of implementing a probabilistic proofs solution as part of pocket-score scalability efforts, we should collect proof data points to determine if this is an effective approach to save space and time.

## Origin Document

[Probabilistic Proofs Proposal](https://www.notion.so/pocketnetwork/Idea-Probabilistic-Proofs-f3fa87447f1c4c63b38b1ff46c049f67)

[Guardrails Projects](https://docs.google.com/document/d/1uBomaVieGAjsyHeqSlwmqOyPOln1CemVlWXZjQXUMRY/edit#heading=h.h125pd3bsv3a)

[Guardrails Recommendations](https://docs.google.com/document/d/1QcsPfhj636zBazw2jAay8H6gdBKXcIMmohY0o321hhQ/edit)

## Goal

- Create proof data visualizations that show how much block space and processing is used by proofs today

## Deliverable

- [ ] What % of the block space is consumed by the proofs? Request for:
   - [ ] x-axis block #
   - [ ] y-axis  size in mb
   - [ ] Line graph #1: `block size` 
   - [ ] Line graph #2: `size of proofs`
   - [ ] Compare how close below #1, #2 is. If it is close, probabilistic distributions are a good way to save space
- [ ] What % time of block processing is consumed by proof verification?
   - [ ] x-axis` block #
   - [ ] y-axis` # seconds to process block
   - [ ] Line graph #1: `time to process block`
   - [ ] Line graph #2: `time to process proofs`
   - [ ] Compare how close below #1, #2 is. If it is close, probabilistic distributions are a good way to save time.
- [ ] Document data visualizations etc. [here ](https://www.notion.so/pocketnetwork/Probabilistic-Proofs-Data-b7f0230e56a24f8f941128c801d0fbac)

## Non-goals / Non-deliverables

- Automating or logging the above data points

## General issue deliverables

- [ ] Update the appropriate CHANGELOG
- [ ] Update any relevant READMEs (local and/or global)
- [ ] Update any relevant global documentation & references
- [ ] If applicable, update the source code tree explanation
- [ ] If applicable, add or update a state, sequence or flowchart diagram using [mermaid](https://mermaid-js.github.io/mermaid/)

---

**Creator**: @jessicadaugherty

**Comment by Olshansk** [comment]
Completed by @rawthil here: https://gist.github.com/RawthiL/05fbfaf76ddc199eda4a303559bff0b3
